# Generated by Django 3.1.4 on 2020-12-22 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=10, unique=True)),
                ('car_name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=300)),
                ('short_desc', models.CharField(default='', max_length=100)),
                ('mileage', models.IntegerField(default=0)),
                ('top_speed', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[['Audi', 'Audi'], ['Benz', 'Benz'], ['Chevrolet', 'Chevrolet'], ['Dodge', 'Dodge'], ['Ford', 'Ford'], ['Honda', 'Honda'], ['Infiniti Motor Company', 'Infiniti Motor Company'], ['Jaguar', 'Jaguar'], ['Kia Motors', 'Kia Motors'], ['Landrover', 'Landrover'], ['Maruti', 'Maruti'], ['Nissan', 'Nissan']], max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(default='', upload_to='car/images')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default='', max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.IntegerField(default=None)),
                ('address', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
                ('zip_code', models.IntegerField(default=None)),
                ('mode_of_delivery', models.CharField(choices=[['Cash On Delivery', 'Cash On Delivery']], max_length=50)),
                ('ordered_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracker_id', models.CharField(default='', max_length=15)),
                ('location', models.CharField(default='', max_length=50)),
                ('message', models.CharField(default='', max_length=150)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(default='', max_length=100)),
                ('subject', models.CharField(default='', max_length=100)),
                ('message', models.CharField(default='', max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
