# Generated by Django 3.1.4 on 2020-12-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20201223_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='no_of_days',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
    ]
