# Generated by Django 3.1.4 on 2020-12-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_auto_20201223_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_name',
            field=models.CharField(max_length=50),
        ),
    ]
