# Generated by Django 3.1.4 on 2020-12-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_auto_20201225_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[['Audi', 'Audi'], ['Benz', 'Benz'], ['Chevrolet', 'Chevrolet'], ['Dodge', 'Dodge'], ['Ford', 'Ford'], ['Honda', 'Honda'], ['Hyundai', 'Hyundai'], ['Jaguar', 'Jaguar'], ['Kia Motors', 'Kia Motors'], ['Landrover', 'Landrover'], ['Maruti', 'Maruti'], ['Nissan', 'Nissan']], max_length=50),
        ),
    ]
